<?php
/**
 * O2TI Pre Order.
 *
 * Copyright © 2024 O2TI. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * @license   See LICENSE for license details.
 */

/** @var \Magento\Sales\Block\Order\Email\Items\DefaultItems $block */

/** @var \Magento\Quote\Model\Quote\Item  $item */
$item = $block->getItem();
$order = $item->getQuote();
?>
<tr>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <p class="product-name"><?= $escaper->escapeHtml($item->getName()) ?></p>
        <p class="sku"><?= $escaper->escapeHtml(__('SKU')) ?>: <?= $escaper->escapeHtml($block->getSku($item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
                <?php foreach ($block->getItemOptions() as $option): ?>
                    <dt><strong><em><?= $escaper->escapeHtml($option['label']) ?></em></strong></dt>
                    <dd>
                        <?= /* @noEscape */  nl2br($escaper->escapeHtml($option['value'])) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock): ?>
            <?= $addInfoBlock->setItem($item)->toHtml() ?>
        <?php endif; ?>
        <?= $escaper->escapeHtml($item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= (int) $item->getQty() ?></td>
    <td class="item-price">
        <?= /* @noEscape */ $block->getItemPrice($item) ?>
    </td>
</tr>
