<?php
/**
 * O2TI Pre Order.
 *
 * Copyright © 2024 O2TI. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * @license   See LICENSE for license details.
 */

use O2TI\PreOrder\Block\Quote\Email\Items;

/** @var \O2TI\PreOrder\Block\Quote\Email\Items $block */
?>
<?php $quote = $block->getQuote() ?>
<?php if ($quote): ?>
    <?php $items = $quote->getAllItems(); ?>
    <table class="email-items">
        <thead>
            <tr>
                <th class="item-info">
                    <?= $escaper->escapeHtml(__('Items')) ?>
                </th>
                <th class="item-qty">
                    <?= $escaper->escapeHtml(__('Qty')) ?>
                </th>
                <th class="item-price">
                    <?= $escaper->escapeHtml(__('Price')) ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($items as $item): ?>
            <?php if (!$item->getParentItem()): ?>
                <tbody>
                    <?= $block->getItemHtml($item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
<?php endif; ?>
