<?php
/**
 * O2TI Pre Order.
 *
 * Copyright © 2024 O2TI. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * @license   See LICENSE for license details.
 */

/** @var O2TI\PreOrder\Block\Adapted\Quote\Email\Items\Tax $block */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Squiz.PHP.GlobalKeyword.NotAllowed
$source = $block->getSource();
global $taxIter;
$taxIter++;
?>

<tr class="totals-tax">
    <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
        <?= $escaper->escapeHtml(__('Tax')) ?>
    </th>
    <td <?= /* @noEscape */ $block->getValueProperties() ?> data-th="<?= $escaper->escapeHtmlAttr(__('Tax')) ?>">
        <?= /* @noEscape */ $block->formatPrice($source->getShippingAddress()->getTaxAmount()) ?>
    </td>
</tr>