<?php
/**
 * O2TI Pre Order.
 *
 * Copyright © 2024 O2TI. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * @license   See LICENSE for license details.
 */

/**
 * Fix Quote ID Template
 *
 * @var \O2TI\PreOrder\Block\FixQuoteId $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], '
    require(["O2TI_PreOrder/js/fix-quote-id"], function(fixQuoteId) {
        fixQuoteId.init("' . $escaper->escapeJs((string)$block->getQuoteId()) . '");
    });
', false); ?>
